### ISSUE TITLE
Species clustering issue in plots

### ISSUE THREAD

**Issue by mgils4** [Avans-ATLS/GermGenie#11]
Hi, 

I have noticed that, when classifying different genus's with the same species, name, all species with the same name still get clustered together in the plot. Like when I have _Angelica sylvestris_ and _ Pinus sylvestris_ and _Pinanga sylvestris_, the resulting abundances.tsv file has made seemingly accurate distinction between the species, but when plotting it seems to only take the species name, and seeing as all these plants have matching species names, it all gets clustered into one part of the bar, even though they are all different genus's. Maybe plotting based on Genus_species might be more useful?

Thanks for the great tool, and keep up the good work!

**Comment by sanderboden** [comment]
In the default database, the species column contains both genus and species names. This prevents the issue you've described. Have you built your database in a similar way, or does your species column only contain the species name?

Building a database with the species column like "[genus] [species]" will likely solve your issue. Let me know if you have further questions.
